# String Similarity Algorithms

## N-grams

<img src="data/figure5-1.jpg" height="400" width="400"> *Figure displaying the N-grams concept [1]* </img>

In [1]:
""" This implementation adds a space to the beginning and end of the string before 
extracting the n-grams but the concept illustrated above remains the same. """

def N_grams(X, n):
    X = X.center((len(X)+2)) # adding spaces
    ngrams = []
    for i, x in enumerate(X):
        if len(X[i:]) >= n:
            ngrams.append(X[i:i+n])
    return(ngrams)

### N-grams Example <br>

Suppose we have two strings $X$ = `"Apple Corporation, CA"` and $Y$ = `"Apple Corp, CA"`. The corresponding **N-grams** for `n = 3` for each string would be:

In [93]:
X = "Apple Corporation, CA"
Y = "Apple Corp, CA"

X_n = N_grams(X, n=3)
Y_n = N_grams(Y, n=3)

print("N-grams for string X: \n")
for ngram in X_n:
    print("'" + ngram + "'", end=" ")
    
print("\n")  
print("N-grams for string Y: \n")
for ngram in Y_n:
    print("'" + ngram + "'", end=" ")

N-grams for string X: 

' Ap' 'App' 'ppl' 'ple' 'le ' 'e C' ' Co' 'Cor' 'orp' 'rpo' 'por' 'ora' 'rat' 'ati' 'tio' 'ion' 'on,' 'n, ' ', C' ' CA' 'CA ' 

N-grams for string Y: 

' Ap' 'App' 'ppl' 'ple' 'le ' 'e C' ' Co' 'Cor' 'orp' 'rp,' 'p, ' ', C' ' CA' 'CA ' 

## Jaccard Similarity <br>

To determine how similar two strings $X$ and $Y$ are we can transform $X$ and $Y$ into their respective N-gram sets. Then we can use a set similarity metric like **Jaccard Similarity** to measure the similarity between the two sets, that is, the similarity between corresponding strings $X$ and $Y$.

<br> Formulation:
<br>
$$Jaccard Similarity(X_n, Y_n) =  \frac{\left | X_n \cap Y_n \right |}{\left | X_n \cup Y_n \right |}$$

* $X_n$ is the set of N-grams for string $X$
* $Y_n$ is the set of N-grams for string $Y$

In [94]:
def jaccard_sim(X, Y, n):
    X_n = set(N_grams(X, n))
    Y_n = set(N_grams(Y, n))
    XinterY = X_n.intersection(Y_n)
    XunionY = X_n.union(Y_n)
    return(len(XinterY )/len(XunionY))

### Jaccard Similarity Example 

In [92]:
X = 'Apple Corporation, CA'
Y = 'Apple Corp, CA'

print("Jaccard Similarity: {:.4f}".format(jaccard_sim(X, Y, n=3)))

Jaccard Similarity: 0.5217


Notice how the Jaccard Similiarty between $X$ and $Y$ changes as the value of $n$ changes.

In [89]:
for i in range(1,6):
    print("JaccSim(X, Y) for n = {}: {:.2f}".format(i, jaccard_sim(X,Y, n=i)))

JaccSim(X, Y) for n = 1: 0.69
JaccSim(X, Y) for n = 2: 0.62
JaccSim(X, Y) for n = 3: 0.52
JaccSim(X, Y) for n = 4: 0.43
JaccSim(X, Y) for n = 5: 0.35


## Edit (Levenshtein) Distance 

The **Edit Distance** between $X$ and $Y$ is the minimum number of edits to string $X$ to be transformed into string $Y$.

Suppose the length of $X = n$, in other words, $X$ is composed of $n$ characters. Additionally, suppose the length of $Y = m$, that is, $Y$ has $m$ characters. We can define $X$ and $Y$ in terms of their characters as follows:

- $X = x_0 x_1 x_2 \ldots x_n$ <br>
- $Y = y_0 y_1 y_2 \ldots y_m$. 

> Going forward we will use $i$ to index $X$ and $j$ to index $Y$.

<br> The algorithm works by considering all possible length-i prefixes of $X$ and length-j prefixes of $Y$ with the following recurence equations (we will use a matrix to store the values):

<br>

### Initialization <br>

* $d(i, 0) = i$ <br>
* $d(0, j) = j$ <br> <br>

### Recurrence Equations <br>

$\forall i \in \left \{0, 1, 2, \ldots n \right \}$ <br>
$\quad \quad \forall j \in \left \{0, 1, 2, \ldots m \right \}$ 



$\quad \quad \quad d(i, j) = \left\{
        \begin{array}{ll}
             d(i-1, j-1) + c(x_i, y_j)  \\
             d(i-1, j) + 1 \\
             d(i, j-1) + 1
        \end{array}
    \right.$
    
<br> 
 $$c(x_i, y_j) = \left\{
        \begin{array}{ll}
             0  & \quad  x_i = y_j \\
             1 & \quad \text{otherwise}
        \end{array}
    \right.$$
    
<br> $d(n, m)$ will be the Edit Distance between $X$ and $Y$.

### Example

<img src="data/edit_dist_example.png" height="300" width="300"> *The arrows refer to the optimal alignment of the strings so those can be ignored* </img>

### Implementation with NumPy!

In [97]:
import numpy as np

In [125]:
def edit_distance(X, Y):
    n = len(X)
    m = len(Y)
    dist_matrix = np.zeros((n + 1, m + 1), dtype=int)
    first_row = np.arange(m+1)
    first_col = np.arange(n+1)
    # initialzie the first row and col in the matrix
    dist_matrix[0,:] = first_row
    dist_matrix[:,0] = first_col
    
    for i in range(1,n+1):
        for j in range(1,m+1):
            upper = dist_matrix[i-1,j]
            left = dist_matrix[i,j-1]
            upper_left = dist_matrix[i-1, j-1]
            
            if X[i-1] == Y[j-1]:
                delta = 0
                dist_matrix[i,j] = min(upper, left, upper_left) + delta
                    
            else:
                delta = 1
                dist_matrix[i,j] = min(upper, left, upper_left) + delta
    return(dist_matrix[n,m], dist_matrix)

### Algorithm in Action

In [116]:
x = 'dva'
y = 'dave'

edit_dist, dist_matrix = edit_distance(x, y)
print("Distance Matrix: \n {}".format(dist_matrix))
print("\n")
print("Edit Disance: {}".format(edit_dist))

Distance Matrix: 
 [[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 1 1 2]
 [3 2 1 2 2]]


Edit Disance: 2


## Edit Similarity <br>

$$EditSimilarity(X, Y) = 1 - \frac{ EditDistance(X, Y) }{ max(length(X), length(Y))}$$ <br>

In [121]:
def edit_similarity(X,Y):
    edit_dist = edit_distance(X,Y)[0]
    return(1-(edit_dist/max(len(X), len(Y))))

In [124]:
X = 'Apple Corporation, CA'
Y = 'Apple Corp, CA'

print("Edit Similarity: {:.4f}".format(edit_similarity(X, Y)))

Edit Similarity: 0.6667


## References  <br>

[1] Gustavsson, J. (1996). *Figure 5-1*. [Image] Text Categorization Using Acquaintance. http://plaza.ufl.edu/jgu/public_html/C-uppsats/cup.html